select * from customer limit 20 


-- what is the total revenue generated by each gender?
select gender , sum(purchase_amount) as revenue  from customer group by gender

-- which customers used discount but still spent more than the average purchase ammount ?
select customer_id , discount_applied , purchase_amount
from customer
where discount_applied ='Yes' and 
purchase_amount>=(select avg(purchase_amount) from customer)

--which are the top 5 products with hightest average rating  
select item_purchased as item , avg(review_rating) as avg_rating 
from customer
group by item_purchased
order by avg_rating desc
limit 5

select item_purchased as item , round(avg(review_rating::numeric),2) as avg_rating 
from customer
group by item_purchased
order by avg_rating desc
limit 5

-- compare the avg purchase amount between standard and expresss shipping .
select  shipping_type ,round(avg(purchase_amount::numeric),2) as avg_amount 
from customer where shipping_type in ('Standard','Express')
group by shipping_type order by avg_amount desc

-- compare the avg purchase amount between standard and expresss shipping  diffrernt types of shipping .
select  shipping_type ,round(avg(purchase_amount::numeric),2) as avg_amount 
from customer group by shipping_type order by avg_amount desc


-- do subscribed customers spend more or non subscribers?
select  subscription_status , round(avg(purchase_amount::numeric),2)  as avg_amount
from customer group by subscription_status  order by avg_amount desc

-- do subscribed customers spend more or non subscribers? compare avg spend and whats the total revenue bewteen them
select subscription_status, count(customer_id) as total_customers ,round(avg(purchase_amount::numeric),2)  as avg_amount, sum(purchase_amount) as total_revenue
from customer
group by subscription_status order by avg_amount desc

--which  product rely heavily on discount to sell
select item_purchased ,
round(100*sum(case when discount_applied='Yes' then 1 else 0 end )/count(*),2) as discount_applied
from customer 
group by item_purchased order by discount_applied desc limit 5



--Which products generated the most revenue when customers used discounts? display top 5
select item_purchased , sum(purchase_amount) as total_revenue from customer 
where discount_applied ='Yes'
group by item_purchased order by total_revenue desc limit 5

--segment customers into new, returning and loyal and show the count of each segment 
with customer_type as
(select customer_id, previous_purchases,
case 
when previous_purchases between 1 and 5 then'new'
when previous_purchases between 5 and  10 then 'returning'
else 'loyal'
end as customer_segment
from customer
)
select customer_segment, count(*)as total_customers
from customer_type 
group by customer_segment
order by total_customers desc

-- what are the top 3 purchased products in each category

 with item_counts as(
select category , item_purchased, count(customer_id) as total_orders,
row_number() over(partition by category order by count(customer_id) desc) as item_rank
from customer
group by category , item_purchased
 )
 select item_rank,category,item_purchased , total_orders from item_counts
 where item_rank <=3;

 -- are customers who r repeat buyers (more than 5 previous purchases) also likely to subscribe?

 select * from customer limit 5

 select subscription_status , count(customer_id) as repeat_buyers
 from customer 
 where previous_purchases >5 GROUP BY subscription_status

 -- what  is the revenue by each age group
 select age_group , count(customer_id)  as total_customers , sum(purchase_amount) as total_revenue from customer
 group by age_group order by total_revenue desc

SELECT current_user;
SELECT current_database();

-- localhost:5432